name: Create and publish a release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true
jobs:
  publish:
    name: Create and publish a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Create tag and publish to the Maven Central Repository
        run: |
          mvn --batch-mode versions:set -DnewVersion=${{ github.event.inputs.version }}
          git config --global user.email "bob@hdi.de"
          git config --global user.name "Bob the Builder"
          git add pom.xml
          git commit -m "updating version to ${{ github.event.inputs.version }} in pom"
          git tag -a v${{ github.event.inputs.version }} -m "tagging version ${{ github.event.inputs.version }}"
          git push --tags
          mvn --batch-mode deploy -Ppublish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_KEY_PASSWORD }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: |
            Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false